[package]
name = "reinfors-py"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "_reinfors"
crate-type = ["cdylib"]

[dependencies]
reinfors-core = { path = "../reinfors-core" }
reinfors-games = { path = "../reinfors-games" }
pyo3 = { version = "0.25", features = ["extension-module", "abi3-py310"] }
numpy = "0.25"
