"""Generate the CarRacing HUD score glyph atlas from Gym's own font rendering.

Gym draws the score with pygame's default font (FreeSansBold) at 42px on the
1000x800 window surface, which then gets smooth-scaled to the 96x96 observation.
This script renders each score character ('0'-'9', '-') the same way, pre-scales
it into the renderer's supersample space with pygame's smoothscale (the same
filter gym applies to the whole frame), and emits the result as generated Rust
constants. Raster snapshots of glyph shapes carry no font-program code, so the
atlas is embeddable in this repository; the TTF itself is not.

Regenerate with:
    uv run --no-project --with pygame python scripts/gen_score_font.py
"""

from __future__ import annotations

import pathlib

import pygame

WINDOW_W, WINDOW_H = 1000.0, 800.0
FRAME, SUPERSAMPLE = 96, 4
SX = FRAME * SUPERSAMPLE / WINDOW_W
SY = FRAME * SUPERSAMPLE / WINDOW_H
CHARS = "0123456789-"
OUT = pathlib.Path(__file__).resolve().parent.parent / ("crates/reinfors-games/src/car_racing/score_font.rs")


def main() -> None:
    import os

    os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
    pygame.display.init()
    pygame.display.set_mode((1, 1))
    pygame.font.init()
    font = pygame.font.Font(pygame.font.get_default_font(), 42)
    entries = []
    for ch in CHARS:
        surf = font.render(ch, True, (255, 255, 255), (0, 0, 0)).convert(24)
        advance = font.metrics(ch)[0][4]
        w = round(surf.get_width() * SX)
        h = round(surf.get_height() * SY)
        scaled = pygame.transform.smoothscale(surf, (w, h))
        alpha = bytes(scaled.get_at((x, y)).r for y in range(h) for x in range(w))
        entries.append((ch, w, h, advance * SX, alpha))

    lines = [
        "// Generated by scripts/gen_score_font.py — do not edit by hand.",
        "//",
        "// Each glyph is Gym's own 42px FreeSansBold rendering, smooth-scaled into",
        "// supersample space exactly as pygame scales the frame. `alpha` is row-major",
        "// coverage; `advance` is the scaled pen advance in supersample pixels.",
        "",
        "pub(super) struct ScoreGlyph {",
        "    pub ch: char,",
        "    pub width: usize,",
        "    pub height: usize,",
        "    pub advance: f32,",
        "    pub alpha: &'static [u8],",
        "}",
        "",
        f"pub(super) const SCORE_GLYPHS: [ScoreGlyph; {len(entries)}] = [",
    ]
    for ch, w, h, adv, alpha in entries:
        esc = "".join(f"\\x{b:02x}" for b in alpha)
        lines.append("    ScoreGlyph {")
        lines.append(f"        ch: {ch!r},")
        lines.append(f"        width: {w},")
        lines.append(f"        height: {h},")
        lines.append(f"        advance: {adv}f32,")
        lines.append(f'        alpha: b"{esc}",')
        lines.append("    },")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    sizes = ", ".join(f"{c}:{w}x{h}" for c, w, h, _, _ in entries)
    print(f"wrote {OUT} ({sizes})")


if __name__ == "__main__":
    main()
