"""Generate drift-prone documentation tables from ``reinfors.catalog``.

Run ``python scripts/generate_docs.py`` after changing catalogue metadata. CI uses ``--check``.
The extension module is deliberately not imported, so this works before a Rust build.
"""

from __future__ import annotations

import argparse
import runpy
from collections.abc import Iterable
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CATALOG = runpy.run_path(str(ROOT / "python/reinfors/catalog.py"))
GENERATED = "<!-- Generated by scripts/generate_docs.py; edit python/reinfors/catalog.py. -->\n\n"


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def table(headers: Iterable[str], rows: Iterable[Iterable[str]]) -> str:
    head = [*headers]
    out = ["| " + " | ".join(head) + " |", "| " + " | ".join("---" for _ in head) + " |"]
    out.extend("| " + " | ".join(escape(cell) for cell in row) + " |" for row in rows)
    return "\n".join(out)


def games_page() -> str:
    games: dict[str, Any] = CATALOG["GAMES"]
    encoders: dict[str, Any] = CATALOG["ENCODER_INFO"]

    rows = (
        (
            info.label,
            info.players,
            info.dynamics,
            info.chance,
            info.information,
            info.actions,
            info.observation,
            ", ".join(f"`{name}`={default:g}" for name, default in info.reward_keys),
            info.adapters,
        )
        for info in games.values()
    )
    encoder_rows = (
        (info.label, info.game, info.shape, f"`{info.constructor}`", info.summary) for info in encoders.values()
    )
    return (
        GENERATED
        + "# Games\n\n"
        + "Game rules, rewards and encoders are separate components. The table describes the "
        + "built-in defaults; constructors expose the configurable details.\n\n"
        + table(
            (
                "Game",
                "Players",
                "Decisions",
                "Chance",
                "Information",
                "Actions",
                "Observation",
                "Reward arguments (defaults)",
                "Adapter",
            ),
            rows,
        )
        + "\n\nThe action interface is one fixed discrete vocabulary per game; continuous and "
        + "parameterized actions are outside the current "
        + "[action-space boundary](../reference/limits.md#fixed-observation-and-action-spaces). "
        + "The Decisions column describes one game-wide mode: a game cannot currently switch "
        + "between sequential and simultaneous "
        + "[decision phases](../reference/limits.md#decision-phases).\n\n"
        + "Reward arguments are the keyword weights accepted by `rf.Reward` for that game; "
        + "unknown names are rejected at `Engine` construction. Poker's `scale` multiplies the "
        + "native chip-delta event.\n\n"
        + "## Observation encoders\n\n"
        + "Every game constructor accepts an `encoder=` handle and otherwise selects its registered "
        + "default. The encoder owns the network-facing observation and action frame, while the game "
        + "owns rules and state transitions. Chess currently offers multiple views; the other built-in "
        + "games each expose one. Size a network from `game.observation_space().shape` after "
        + "construction.\n\n"
        + "```python\n"
        + "game = rf.games.Chess(encoder=rf.encoders.RelativeChess())\n"
        + "obs_shape = game.observation_space().shape  # (19, 8, 8)\n"
        + "```\n\n"
        + table(("Encoder", "Game", "Observation shape", "Constructor", "Purpose"), encoder_rows)
        + "\n\nBefore moving action ids between a network and `Env`, read the "
        + "[action-frame contract](../reference/glossary.md#action-frames).\n\n"
        + "## CarRacing notes\n\n"
        + "CarRacing ports Gymnasium's `CarRacing-v3` (discrete). Faithful means the action "
        + "contract, observation content, track-generation algorithm, reward and episode rules, "
        + "and qualitative driving behavior; trajectories, checkpoints, and scores from the "
        + "Gymnasium build do not transfer (different physics engine and float paths).\n\n"
        + "- The rendered HUD score is the canonical Gym score (fixed `tile`/`step` constants, "
        + "off-playfield never shown) regardless of the `rf.Reward` weights you train with.\n"
        + "- Tile progress counts per-wheel contact-entry events, matching Gym's behavior "
        + "including its sticky reset-contact lap quirk.\n"
        + "- Observations are channel-major `(3, 96, 96)` raw 0-255 floats per the framework "
        + "contract; Gymnasium renders the same content as HWC uint8, so pipelines moving "
        + "between the two must permute and cast.\n"
        + "- Snapshot bytes carry only validated dynamic values (poses, velocities, controls, "
        + "joint warm-start impulses, progress); the physics world is reconstructed canonically "
        + "at restore, which is what keeps hostile snapshot bytes safe. Restore is exact over "
        + "those serialized values and always resumes the same trajectory, but that trajectory "
        + "departs from a never-snapshotted run at float rounding order (solver bookkeeping is "
        + "rebuilt, not restored), so restored collection is deterministic rather than "
        + "record-identical to an uninterrupted run.\n"
        + "- The standard-API adapters withhold `car_racing` until frames can be presented in "
        + "Gym's native HWC uint8 layout; use `rf.Env` directly.\n"
        + "\n\nSee [built-in compatibility](compatibility.md) for supported workflows and the "
        + "[Python API](../reference/python-api.md) for constructor parameters.\n"
    )


def algorithms_page() -> str:
    algorithms: dict[str, Any] = CATALOG["ALGORITHMS"]
    batch_types = {"TreeStrapBatch", "DqnBatch", "AlphaZeroBatch", "DeepCfrBatch"}

    def output_link(name: str) -> str:
        if name not in batch_types:
            return name
        return f"[`{name}`](../reference/batch-formats.md#{name.lower()})"

    composition_rows = (
        (
            info.label,
            info.workflow,
            f"`{info.policy_or_solver}`",
            "—" if info.learner is None else f"`{info.learner}`",
            output_link(info.training_output),
            f"[{info.example_label}](../examples/index.md#{info.example_anchor})",
        )
        for info in algorithms.values()
    )
    rows = (
        (
            info.label,
            info.workflow,
            info.players,
            info.dynamics,
            info.chance,
            info.information,
            info.network,
        )
        for info in algorithms.values()
    )
    details = []
    for info in algorithms.values():
        refs = ", ".join(f"[{label}]({url})" for label, url in info.references)
        details.append(f"### {info.label}\n\n{info.summary}\n\n**Sources:** {refs}.")
    return (
        GENERATED
        + "# Algorithms\n\n"
        + "Choose a workflow first: Engine algorithms emit training records while standalone "
        + "solvers own their traversal. Python always owns neural-network training. In the search "
        + "rows, `AlwaysResample`, `Committed`, and `ExpandAll` name handles from "
        + "[`rf.chance_modes`](../reference/glossary.md#chance-modes); DQN and solver rows describe "
        + "their own chance treatment. The glossary also defines records, ensemble heads, "
        + "and MaxN.\n\n"
        + "## Composition and training output\n\n"
        + table(
            ("Algorithm", "Execution", "Policy or solver", "Learner", "Training output", "Example"),
            composition_rows,
        )
        + "\n\nEngine rows name the exact policy/learner handles passed to `rf.Engine`. Standalone "
        + "solvers own their traversal; tabular CFR updates internal tables, while Deep CFR emits "
        + "a caller-trained batch.\n\n"
        + "## Supported semantics\n\n"
        + table(
            ("Algorithm", "Workflow", "Players", "Decisions", "Chance", "Information", "Network output"),
            rows,
        )
        + "\n\n## Algorithm families\n\n"
        + "\n\n".join(details)
        + "\n\nSee [built-in compatibility](compatibility.md), "
        + "[sampling and training](../concepts/sampling-and-training.md), and the "
        + "[inference contract](../reference/inference-contract.md).\n"
    )


def compatibility_page() -> str:
    games: dict[str, Any] = CATALOG["GAMES"]
    algorithms: dict[str, Any] = CATALOG["ALGORITHMS"]
    unknown = {key for game in games.values() for key in game.algorithms} - algorithms.keys()
    if unknown:
        raise ValueError(f"game catalogue references unknown algorithms: {sorted(unknown)}")
    rows = ((game.label, *("Yes" if key in game.algorithms else "—" for key in algorithms)) for game in games.values())
    reached_state_games = ", ".join(game.label for game in games.values() if game.reached_state_starts) or "None"
    return (
        GENERATED
        + "# Built-in compatibility\n\n"
        + "This is the canonical compatibility matrix for Python's built-in handles. It is generated "
        + "from metadata checked against the public registries and actual construction. A compatible composition may "
        + "still reject particular parameters at construction; consult the algorithm and game tables for "
        + "semantic limits.\n\n"
        + table(("Game", *(info.label for info in algorithms.values())), rows)
        + "\n\n**Reached-state starts:** "
        + reached_state_games
        + ". See the optional "
        + "[`Engine` start buffer](../guides/configuration-and-checkpoints.md#reached-state-starts).\n\n"
        + "Exact CFR/CFR+ requires enumerable chance fans. Texas Hold'em therefore uses the "
        + "external-sampling MCCFR variant shown separately.\n\n"
        + "Additional native components can add compositions beyond this built-in matrix when they "
        + "satisfy the relevant core traits and the current "
        + "[native component boundary](../reference/limits.md#native-component-boundary).\n"
    )


OUTPUTS = {
    ROOT / "docs/catalogue/games.md": games_page,
    ROOT / "docs/catalogue/algorithms.md": algorithms_page,
    ROOT / "docs/catalogue/compatibility.md": compatibility_page,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, render in OUTPUTS.items():
        expected = render()
        if args.check:
            if not path.exists() or path.read_text() != expected:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(expected)
    if stale:
        print("Generated documentation is stale:")
        for path in stale:
            print(f"  {path}")
        print("Run: python scripts/generate_docs.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
