"""Generate drift-prone documentation tables from ``reinfors.catalog``.

Run ``python scripts/generate_docs.py`` after changing catalogue metadata. CI uses ``--check``.
The extension module is deliberately not imported, so this works before a Rust build.
"""

from __future__ import annotations

import argparse
import runpy
from collections.abc import Iterable
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CATALOG = runpy.run_path(str(ROOT / "python/reinfors/catalog.py"))
GENERATED = "<!-- Generated by scripts/generate_docs.py; edit python/reinfors/catalog.py. -->\n\n"


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def table(headers: Iterable[str], rows: Iterable[Iterable[str]]) -> str:
    head = [*headers]
    out = ["| " + " | ".join(head) + " |", "| " + " | ".join("---" for _ in head) + " |"]
    out.extend("| " + " | ".join(escape(cell) for cell in row) + " |" for row in rows)
    return "\n".join(out)


def games_page() -> str:
    games: dict[str, Any] = CATALOG["GAMES"]
    rows = (
        (
            info.label,
            info.players,
            info.dynamics,
            info.chance,
            info.information,
            info.actions,
            info.observation,
            info.adapters,
        )
        for info in games.values()
    )
    summaries = "\n\n".join(f"### {info.label}\n\n{info.summary}" for info in games.values())
    return (
        GENERATED
        + "# Games\n\n"
        + "Game rules, rewards and encoders are separate components. The table describes the "
        + "built-in defaults; constructors expose the configurable details.\n\n"
        + table(
            ("Game", "Players", "Decisions", "Chance", "Information", "Actions", "Observation", "Adapter"),
            rows,
        )
        + "\n\n## At a glance\n\n"
        + summaries
        + "\n\nSee [built-in compatibility](compatibility.md) for supported workflows and the "
        + "[Python API](../reference/python-api.md) for constructor parameters.\n"
    )


def algorithms_page() -> str:
    algorithms: dict[str, Any] = CATALOG["ALGORITHMS"]
    rows = (
        (
            info.label,
            info.workflow,
            info.players,
            info.dynamics,
            info.chance,
            info.information,
            info.network,
        )
        for info in algorithms.values()
    )
    details = []
    for info in algorithms.values():
        refs = ", ".join(f"[{label}]({url})" for label, url in info.references)
        details.append(f"### {info.label}\n\n{info.summary}\n\n**Sources:** {refs}.")
    return (
        GENERATED
        + "# Algorithms\n\n"
        + "Choose a workflow first: Engine algorithms emit training records while standalone "
        + "solvers own their traversal. Python always owns neural-network training.\n\n"
        + table(
            ("Algorithm", "Workflow", "Players", "Decisions", "Chance", "Information", "Network output"),
            rows,
        )
        + "\n\n## Algorithm families\n\n"
        + "\n\n".join(details)
        + "\n\nSee [built-in compatibility](compatibility.md), "
        + "[sampling and training](../how-it-works/sampling-and-training.md), and the "
        + "[inference contract](../reference/inference-contract.md).\n"
    )


def compatibility_page() -> str:
    games: dict[str, Any] = CATALOG["GAMES"]
    algorithms: dict[str, Any] = CATALOG["ALGORITHMS"]
    unknown = {key for game in games.values() for key in game.algorithms} - algorithms.keys()
    if unknown:
        raise ValueError(f"game catalogue references unknown algorithms: {sorted(unknown)}")
    rows = ((game.label, *("Yes" if key in game.algorithms else "—" for key in algorithms)) for game in games.values())
    return (
        GENERATED
        + "# Built-in compatibility\n\n"
        + "This is the canonical compatibility matrix for Python's built-in handles. It is generated "
        + "from metadata checked against the public registries and actual construction. A compatible composition may "
        + "still reject particular parameters at construction; consult the algorithm and game tables for "
        + "semantic limits.\n\n"
        + table(("Game", *(info.label for info in algorithms.values())), rows)
        + "\n\n## Optional engine capabilities\n\n"
        + table(
            ("Game", "Reached-state starts"),
            ((game.label, "Yes" if game.reached_state_starts else "—") for game in games.values()),
        )
        + "\n\nExact CFR/CFR+ requires enumerable chance fans. Texas Hold'em therefore uses the "
        + "external-sampling MCCFR variant shown separately.\n\n"
        + "Downstream Rust components can add compositions beyond this built-in Python matrix when they "
        + "satisfy the relevant core traits.\n"
    )


OUTPUTS = {
    ROOT / "docs/catalogue/games.md": games_page,
    ROOT / "docs/catalogue/algorithms.md": algorithms_page,
    ROOT / "docs/catalogue/compatibility.md": compatibility_page,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, render in OUTPUTS.items():
        expected = render()
        if args.check:
            if not path.exists() or path.read_text() != expected:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(expected)
    if stale:
        print("Generated documentation is stale:")
        for path in stale:
            print(f"  {path}")
        print("Run: python scripts/generate_docs.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
